### ISSUE TITLE
块引的文档图标显示的是黑白的图标，而不是和思源一样彩色的图标

### ISSUE THREAD

**Issue by XinLi0111** [chenshinshi/link-icon#10]
win 11 系统，思源 2.10.9-dev1

**Comment by chenshinshi** [comment]
这个问题不是插件的问题而是你的界面字体问题。
文档树应用的图标是一套图标库，我们则直接向正文中插入emoji，显示为用户设置的字体。
像我如果界面文档树图标和正文图标都是twitter emoji就都是全彩的。
而你可能是正文中使用了某种不支持彩色emoji的字体。我这边不能提供解决方案。
