### ISSUE TITLE
小建议：支持自定义链接与图标

### ISSUE THREAD

**Issue by winter60** [chenshinshi/link-icon#12]
尽管有一些网站或本地图标了，不过仍然也有未匹配的，一个个靠作者维护不现实，希望可以增加自定义图标并匹配url(保存在本地文件)，可以上传logo图片。
感谢大佬~

**Comment by chenshinshi** [comment]
@frostime

**Comment by pisceswb** [comment]
👍

**Comment by onemonet** [comment]
+1

**Comment by KuangJieRepository** [comment]
+1，还在开发吗 😄

**Comment by frostime** [comment]
v3.0 更新，close #12

![image](https://github.com/user-attachments/assets/402319ff-a4a9-4a2b-bdfb-088bca4c213f)

![image](https://github.com/user-attachments/assets/59f4eafc-ff6f-4f4d-b76e-b8841758ff87)
