### ISSUE TITLE
3.1.6版本报错

### ISSUE THREAD

**Issue by lentikr** [chenshinshi/link-icon#20]
plugin:link-icon:26 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/bd529bc2-b1af-42bb-92a6-6ed1d090e799)

**Comment by lentikr** [comment]
> ![image](https://private-user-images.githubusercontent.com/78434827/374610698-bd529bc2-b1af-42bb-92a6-6ed1d090e799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTk5MzIsIm5iZiI6MTcyODM5OTYzMiwicGF0aCI6Ii83ODQzNDgyNy8zNzQ2MTA2OTgtYmQ1MjliYzItYjFhZi00MmJiLTkyYTYtNmVkMWQwOTBlNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE1MDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjY2ZkZjJlYTNhZjVjNmIyODE2MWQ0ODVmMTg5YTVmNmI0MTFkMDI5NWQ1YTlkNDhlYzk4ZjUwMTU1OTFiMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rsRML-TxJ5G3lDyei2-o-WmuaMHkH6VMlKh03rNoMG4)

可以按上面的pull request自己修补一下，实测有用

**Comment by TCOTC** [comment]
比较懒，在等 PR 合并（
