### ISSUE TITLE
PDF链接带参数时无法显示PDF图标

### ISSUE THREAD

**Issue by TCOTC** [chenshinshi/link-icon#25]
![image](https://github.com/user-attachments/assets/6b6441b2-3e11-4d7b-9819-5b8503616ed8)

**Comment by chenshinshi** [comment]
原来还能这样定位页数，学到了！
因为原本的代码是直接靠末尾判断文件类型的，这种情况从来没有考虑到，我先试着把".pdf?page"这串字符也加入判断吧。
