### ISSUE TITLE
引用页面没有图标

### ISSUE THREAD

**Issue by intelion2022** [chenshinshi/link-icon#3]
网页链接有图标，但引用页面没有图标，如图：
![image](https://github.com/chenshinshi/link-icon/assets/116488969/83a92027-9999-4437-aa61-3bf01a9eaacf)

**Comment by chenshinshi** [comment]
您好，我这边无法复现，请您提供文档【测试】文档与【如何理解学习党史的三种逻辑】文档以及该文档所应用的图标文件供我测试。

**Comment by intelion2022** [comment]
> 您好，我这边无法复现，请您提供文档【测试】文档与【如何理解学习党史的三种逻辑】文档以及该文档所应用的图标文件供我测试。

[如何理解学习党史的三种逻辑.sy.zip](https://github.com/chenshinshi/link-icon/files/12565866/sy.zip)
[测试.sy.zip](https://github.com/chenshinshi/link-icon/files/12565868/sy.zip)
![已阅-收藏](https://github.com/chenshinshi/link-icon/assets/116488969/a6ea97b5-75f4-4676-8c83-3c18fcd58515)

**Comment by chenshinshi** [comment]
测试下 2.0.0 新版本还有这个问题吗
