### ISSUE TITLE
没有特定图标的会空白了一个位置

### ISSUE THREAD

**Issue by LJpLJ** [chenshinshi/link-icon#4]
能否选择取消这个空白位置，或者有默认图标
![截图_20230907053440](https://github.com/chenshinshi/link-icon/assets/1617882/8623fbe6-e93a-44f3-9862-3253b876a64b)

**Comment by chenshinshi** [comment]
您好，我这边无法复现，请您提供文档供我测试。

**Comment by chenshinshi** [comment]
测试下 2.0.0 新版本还有这个问题吗
