### ISSUE TITLE
图标重复

### ISSUE THREAD

**Issue by everleap** [chenshinshi/link-icon#5]
第一次刷新出现图标后，之后可能会继续刷新出图标，造成引用图表的重复。
![image](https://github.com/chenshinshi/link-icon/assets/96156946/b3c472ca-0b58-4604-9b93-c04bf240d6cc)

**Comment by chenshinshi** [comment]
啊，天啊不知道怎么复现你这种情况，方便把sy.zip发过来让我们测试吗

**Comment by everleap** [comment]
[测试文档.sy.zip](https://github.com/chenshinshi/link-icon/files/12565646/sy.zip)

用了一个新文档来测试，流程复现大概是：
①在一个已经编辑好的块中创建页面链接，然后刷新等引用图标出现；
②再下面新建一个新的块，然后创建新的页面链接并刷新，此时上一个块中的引用图标也会跟随刷新造成重复；

**Comment by chenshinshi** [comment]
你好，请问你可否直接选中多余的图标删除？

**Comment by chenshinshi** [comment]
@frostime F佬有空来看看

**Comment by everleap** [comment]
> 你好，请问你可否直接选中多余的图标删除？

可以删除，但是每次刷新又会重复出现，目前最多的图标是刷出了三个，已经摆烂不想管了😂。

**Comment by frostime** [comment]
复现了这个问题，看起来似乎是思源奇奇怪怪的内部行为，把原本插入的图标合并成正式文本了。
我试着打个补丁看看。
